### ISSUE TITLE
3DS titles will not download

### ISSUE THREAD

**Issue by ghost** [Ghost0159/Ghost-eShop-Homebrew#1]
I think the homebrew isn't compatible with the new hShop website, which produces different links.

**Comment by Ghost0159** [comment]
No, it is compatible and a job is in progress.

**Comment by ghost** [comment]
What do you mean by "job"?

**Comment by Ghost0159** [comment]
Work

**Comment by ghost** [comment]
Understood, please keep working at it, thank you for your service with GhostShop

**Comment by Ghost0159** [comment]
No problem, if you wish you can join the discord server, this way you will be aware of the latest information.

**Comment by Poketubepoggu** [comment]
> I think the homebrew isn't compatible with the new hShop website, which produces different links.

It isn't. hShop made links expire after 3 hours now, because Ghost eShop dev is stealing the links without consent of hShopDev.

**Comment by Ghost0159** [comment]
> > I think the homebrew isn't compatible with the new hShop website, which produces different links.
> 
> It isn't. hShop made links expire after 3 hours now, because Ghost eShop dev is stealing the links without consent of hShopDev.

It's not a problem to steal links, I've talked to the hshop dev, and he just doesn't want to give a direct link for security.

**Comment by Ghost0159** [comment]
On top of that, we don't steal any links, we create our own links with our server.

**Comment by TomTalker** [comment]
Many of the links we have are from our own servers like he mentioned, some are even from my servers and many CIAs were made by me. We did not steal anything.
